name: JacobCrawford
favicon: null
layout_spectrum: 0.4770364344585687
typography_spectrum: 0.02581180538982153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
