name: JacobCrawford
favicon: null
layout_spectrum: 0.24214
typography_spectrum: 0.60331
title: Jacob Crawford - Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2a7ad'
    - '#888f95'
    - '#001219'
    - '#5a6b6f'
    - '#1e3a40'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
