name: JacobCrawford
favicon: null
layout_spectrum: 0.48734
typography_spectrum: 0.21074
title: Jacob Crawford - Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#243a47'
    - '#d4422c'
    - '#cbccce'
    - '#96979b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
